routes/front.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
 
// Route::get('/', function () {
//     return view('welcome');
// });

//Nurshing
Route::get('/', "Front\HomeController@getNursing")->name('main');
Route::get('nursing/', "Front\HomeController@searchNursing")->name('search.nursing');
Route::get('doctor', "Front\HomeController@searchDoctor")->name('search.doctor');
Route::get('doctor-availability', "Front\HomeController@searchDoctorAvailability")->name('doctor.availability');
// Route::get('doctor/search/data', 'Admin\DoctorController@search')->name('doctor.search');

Route::get('nursing-details/{id}', "Front\HomeController@nursingDetails")->name('nursing.list.details');
Route::get('create-appointment/', "Front\HomeController@createAppointment")->name('book.appointment');
//Book Appointment (Save)
Route::post('book-appointment/', "Clinics\PatientDashboardController@bookAppointment")->name('create.appointment');
Route::group(['middleware' =>'auth'], function(){
    Route::get('appointment-status/{id}/{status}', "Front\HomeController@bookingStatus")->name('booking.status');
});

Route::get('/plan-details/{planid}', "Front\HomeController@featuredPlan")->name('featured.plan');
Route::post('/hospital-registration', "Front\PaymentController@store")->name('payment.store');
Route::get('/payment-success/{nhid}', "Front\PaymentController@paymentSuccess")->name('payment.thankyou');
Route::post('/newsletter-save', "Front\NewsLetterController@store")->name('newsletter.store');

/*Doctor Dashboard*/
Route::group(['prefix' => 'clinic','middleware' =>'auth' ], function(){
    //DropZone
    Route::get('galleryimage/fetch/{nhid}', 'Admin\NursingHomeController@fetch')->name('gallery_dropzone.fetch');
    Route::get('galleryimage/delete', 'Admin\NursingHomeController@deleteImage')->name('gallery_dropzone.delete');

    //Change Profile For All Types user
    Route::post('/user-profile', "Clinics\DoctorDashboardController@action")->name('change_profile_pic');

    //use Middleware AdminControl
    Route::group(['prefix' => 'admin', 'middleware' =>'NursingHomeControl'], function(){
        Route::get('/dashboard', "Clinics\ClinicDashboardController@index")->name('nursing.dashboard');
        Route::get('/appointments', "Clinics\ClinicDashboardController@nursingAppointments")->name('nursing_all.appointments');
        Route::get('/patients', "Clinics\ClinicDashboardController@myPatients")->name('nursing.patients');
        Route::get('/patient-search', "Clinics\ClinicDashboardController@search")->name('nursing_patient.search');
        Route::get('/profile', "Clinics\ClinicDashboardController@profileView")->name('nursing.profile.view');
        Route::match(['GET', 'POST'],'/update-profile', "Clinics\ClinicDashboardController@profileUpdate")->name('nursing.profile.update');
        Route::resource('/nursing-doctor', "Clinics\NursingDoctorController");
        Route::get('nursing-doctor/{id}/{status}', 'Clinics\NursingDoctorController@status')->name('nursing-doctor.status');

    });
    //use Middleware Dr.Control
    Route::group(['prefix' => 'doctor', 'middleware' =>'DoctorControl'], function(){
        Route::get('/appointments', "Clinics\DoctorDashboardController@myAppointments")->name('doctors_all.appointments');
        Route::get('/appointment/details/{id}', "Clinics\DoctorDashboardController@appointmentDetails")->name('doctor.appointment.details');
        Route::get('/patients', "Clinics\DoctorDashboardController@myPatients")->name('doctor.patients');
        Route::get('/patient-search', "Clinics\DoctorDashboardController@search")->name('doctor_patient.search');
        Route::get('/dashboard', "Clinics\DoctorDashboardController@index")->name('doctor.dashboard');
        Route::get('/profile', "Clinics\DoctorDashboardController@profileView")->name('doctor.profile.view');
        Route::match(['GET', 'POST'],'/update-profile', "Clinics\DoctorDashboardController@profileUpdate")->name('doctor.profile.update');
    });    

});

Route::group(['prefix' => 'clinic','middleware' =>['auth', 'PatientControl']], function(){
    Route::get('/patient-appointments', "Clinics\PatientDashboardController@myAppointments")->name('patient.appointments');
    Route::get('/patient-dashboard', "Clinics\PatientDashboardController@index")->name('patient.dashboard');
    // Route::get('appointment-status/{id}/{status}', "Clinics\PatientDashboardController@bookingStatus")->name('booking.status');
    //Profile saection
    Route::get('/patient-profile', "Clinics\PatientDashboardController@profileView")->name('patient.profile.view');
    Route::match(['GET', 'POST'],'/update-patient-profile', "Clinics\PatientDashboardController@profileUpdate")->name('patient.profile.update');
});
// Route::get('/skpayment-success', "Front\PaymentController@paymentSuccess")->name('payment.thankyou1');

    // echo "sdfdsaf";

Route::get('/search', function () {
    return view('front.search');
})->name('search');


Route::get('/list-car',"Auth\LoginController@mysiteUser")->name('customer-login');
Route::get('/user-login',"Auth\LoginController@siteFrontUser")->name('front-customer-login');
Route::get('/user-signup',"Auth\LoginController@siteFrontUserSignup")->name('front-customer-signup');
Route::post('/email-otp',"Auth\RegisterController@userVerification")->name('user.verify');

Route::get('/myLocation',"Front\CarController@currentLocation")->name('myLocation');

Route::group(['middleware' => 'FrontControl'], function(){    
    Route::get('/available-car',"Front\CarController@searchCar")->name('find-car');
    Route::get('/available-car-map',"Front\CarController@carsOnMap")->name('map-car');
    Route::get('/car-details',"Front\CarController@carDetails")->name('car.details');
    Route::get('/add-tocart',"Front\OrderController@fillCart")->name('add.to.cart');
    Route::post('/order-now',"Front\OrderController@saveOrder")->name('order.now');

    //Route::get('stripe', 'Front\OrderController@PayNow')->name('pay.now');
    Route::get('stripe', 'Front\OrderController@stripePost')->name('stripe.post');
    
});
//paypal
Route::get('PayPal', 'Front\OrderController@paypalPost')->name('paypal-post');


Route::get('payment', 'Front\PayPalController@payment')->name('payment');
Route::get('cancel', 'Front\PayPalController@cancel')->name('payment.cancel');
Route::get('payment/success', 'Front\PayPalController@success')->name('payment.success');



Route::get('/pdfdownload/{url}',"Front\OrderController@pdfDownload");


Route::get('/how-it-works',function () {
    return view('front.sample-page');
})->name('how-it-works');


Route::get('/terms-of-service',function () {
    return view('front.term-of-service');
})->name('term.service');

Route::get('/privacy-policy',function () {
    return view('front.privacy-policy');
})->name('privacy.policy');

Route::get('/login/{social}','Auth\LoginController@socialLogin')->where('social','twitter|facebook|linkedin|google|github|bitbucket');
Route::get('/login/{social}/callback','Auth\LoginController@handleProviderCallback')->where('social','twitter|facebook|linkedin|google|github|bitbucket');

routes/web.php
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('locale/{locale}', function ($locale){
    Session::put('locale', $locale);
    return redirect()->back();
});

include('front.php');

Route::get('/admin', function () {
    return view('auth.login');
});
Auth::routes();
Auth::routes(['verify' => true]);

Route::get('/home', 'Controller@index')->name('home');
Route::get('admin/masters/model-by-brand', 'Admin\Masters\ModelController@modelByBrand')->name('get-model-by-brand-ajax');
//Route::get('dashboard', 'Admin\DashboardController@index')->name('dashboard');

//drozone auto upload
Route::post('nursinghome/gallery-image', 'Admin\NursingHomeController@createGalleryImage')->name('projects.storeMedia');
Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'AdminControl']], function () {
    Route::get('dashboard', 'Admin\DashboardController@index')->name('admin.panel');

    Route::resource('profile', 'Admin\ProfileController', ['names' => [
        'create' => 'adminprofile.create',
        'index' => 'adminprofile.index',
        'update' => 'adminprofile.update',
        'edit' => 'adminprofile.edit',
        'store' => 'adminprofile.store',
        'show' => 'adminprofile.show',
        'destroy' => 'adminprofile.destroy',
    ]]);
    // Route::post('profilepic', 'Admin\ProfileController@action')->name('change_profile_pic');
    
    //Speciality
    Route::resource('masters/speciality', 'Admin\Masters\SpecialityController');
    Route::get('masters/speciality/search/data', 'Admin\Masters\SpecialityController@search')->name('admin.speciality_search');
    Route::get('masters/delete-speciality/{id}', 'Admin\Masters\SpecialityController@delete')->name('speciality.delete');
    Route::get('masters/speciality/{id}/{status}', 'Admin\Masters\SpecialityController@status')->name('speciality.status');
   
    //Departments
    Route::resource('masters/departments', 'Admin\Masters\DepartmentController');
    Route::get('masters/departments/search/data', 'Admin\Masters\DepartmentController@search')->name('admin.departments_search');
    Route::get('masters/delete-departments/{id}', 'Admin\Masters\DepartmentController@delete')->name('departments.delete');
    Route::get('masters/departments/{id}/{status}', 'Admin\Masters\DepartmentController@status')->name('departments.status');
    
    //Equipments
    Route::resource('masters/equipments', 'Admin\Masters\EquipmentController');
    Route::get('masters/equipments/search/data', 'Admin\Masters\EquipmentController@search')->name('admin.equipments_search');
    Route::get('masters/delete-equipments/{id}', 'Admin\Masters\EquipmentController@delete')->name('equipments.delete');
    Route::get('masters/equipments/{id}/{status}', 'Admin\Masters\EquipmentController@status')->name('equipments.status');
    
    //subscription plans
    Route::resource('masters/plans', 'Admin\Masters\SubscriptionPlansController');
    Route::get('masters/plans/search/data', 'Admin\Masters\SubscriptionPlansController@search')->name('admin.plan_search');
    Route::get('masters/delete-plans/{id}', 'Admin\Masters\SubscriptionPlansController@delete')->name('plans.delete');
    //settings
    Route::resource('settings', 'Admin\SettingController');
    //Colors
    Route::resource('masters/colors', 'Admin\Masters\ColorsController');
    Route::get('masters/colors/search/data', 'Admin\Masters\ColorsController@search')->name('admin.colors_search');
    Route::get('masters/delete-colors/{id}', 'Admin\Masters\ColorsController@delete')->name('colors.delete');
    Route::get('masters/colors/{id}/{status}', 'Admin\Masters\ColorsController@status')->name('colors.status');

    //Engine Types
    Route::resource('masters/engine-types', 'Admin\Masters\EngineTypesController');
    Route::get('masters/engine-types/search/data', 'Admin\Masters\EngineTypesController@search')->name('admin.type_search');
    Route::get('masters/delete-engine-types/{id}', 'Admin\Masters\EngineTypesController@delete')->name('engine-types.delete');
    Route::get('masters/engine-types/{id}/{status}', 'Admin\Masters\EngineTypesController@status')->name('engine-types.status');

    //Vehicle Types
    Route::resource('masters/vehicle-types', 'Admin\Masters\VehicleTypesController');
    Route::get('masters/vehicle-types/search/data', 'Admin\Masters\VehicleTypesController@search')->name('admin.vehicle-type_search');
    Route::get('masters/delete-vehicle-types/{id}', 'Admin\Masters\VehicleTypesController@delete')->name('vehicle-types.delete');
    Route::get('masters/vehicle-types/{id}/{status}', 'Admin\Masters\VehicleTypesController@status')->name('vehicle-types.status');

    //Transmission
    Route::resource('masters/transmission', 'Admin\Masters\TransmissionController');
    Route::get('masters/transmission/search/data', 'Admin\Masters\TransmissionController@search')->name('admin.transmission_search');
    Route::get('masters/delete-transmission/{id}', 'Admin\Masters\TransmissionController@delete')->name('transmission.delete');
    Route::get('masters/transmission/{id}/{status}', 'Admin\Masters\TransmissionController@status')->name('transmission.status');
  
    //Model
    
    Route::resource('masters/model', 'Admin\Masters\ModelController');
    Route::get('masters/model/search/data', 'Admin\Masters\ModelController@search')->name('admin.model_search');
    Route::get('masters/delete-model/{id}', 'Admin\Masters\ModelController@delete')->name('model.delete');
    Route::get('masters/model/{id}/{status}', 'Admin\Masters\ModelController@status')->name('model.status');
    
   
    /* //Cars
    Route::resource('masters/car', 'Admin\Masters\CarController');
    Route::get('masters/car/search/data', 'Admin\Masters\CarController@search')->name('admin.car_search');
    Route::get('masters/delete-car/{id}', 'Admin\Masters\CarController@delete')->name('car.delete');
    Route::get('masters/car/{id}/{status}', 'Admin\Masters\CarController@status')->name('car.status'); */
    
    //Nursing Home
    Route::resource('nursinghome', 'Admin\NursingHomeController');
    Route::get('nursinghome/search/data', 'Admin\NursingHomeController@search')->name('nursinghome.search');
    Route::get('delete-nursinghome/{id}', 'Admin\NursingHomeController@delete')->name('nursinghome.delete');
    Route::get('nursinghome/{id}/{status}', 'Admin\NursingHomeController@status')->name('nursinghome.status');
    // Route::post('nursinghome/gallery-image', 'Admin\NursingHomeController@createGalleryImage')->name('projects.storeMedia');
    Route::get('gallery-image/fetch/{nhid}', 'Admin\NursingHomeController@fetch')->name('dropzone.fetch');
    Route::get('gallery-image/delete', 'Admin\NursingHomeController@deleteImage')->name('dropzone.delete');

    //Doctors
    Route::resource('doctor', 'Admin\DoctorController');
    Route::get('doctor/search/data', 'Admin\DoctorController@search')->name('doctor.search');
    Route::get('delete-doctor/{id}', 'Admin\DoctorController@delete')->name('doctor.delete');
    Route::get('doctor/{id}/{status}', 'Admin\DoctorController@status')->name('doctor.status');
    //Patient
    Route::resource('patient', 'Admin\PatientController');
    Route::get('patient/search/data', 'Admin\PatientController@search')->name('patient.search');
    Route::get('delete-patient/{id}', 'Admin\PatientController@delete')->name('patient.delete');
    Route::get('patient/{id}/{status}', 'Admin\PatientController@status')->name('patient.status');
    
    //Daynamic Contents translation manager
    Route::get('site-contents', 'Admin\LangContentsController@index')->name('contents.index');
    //Cars
    Route::resource('car', 'Admin\CarController');
    Route::get('car/search/data', 'Admin\CarController@search')->name('car.search');
    Route::get('delete-car/{id}', 'Admin\CarController@delete')->name('car.delete');
    Route::get('car/{id}/{status}', 'Admin\CarController@status')->name('car.status');
    Route::post('car/list-status/', 'Admin\CarController@listingStatus')->name('car.listingStatus');
    
    //Orders
    Route::resource('order', 'Admin\OrderController');
    Route::get('order/search/data', 'Admin\OrderController@search')->name('order.search');
    Route::get('order/{id}/{status}', 'Admin\OrderController@orderStatus')->name('order.status');

    //Account
    Route::resource('account', 'Admin\AccountController');
    Route::get('account/search/data', 'Admin\AccountController@search')->name('account.search');
    Route::get('account/owner-payment/{id}/{owner_payment}', 'Admin\AccountController@ownerPayment')->name('account.owner_payment_status');
    //Account
    Route::resource('settings', 'Admin\SettingController');

    //Import region
    Route::get('masters/import-brands-models', 'Admin\Masters\ImportBrandsModelsController@index')->name('import-brands-models.index');
    Route::post('masters/import-brands-models', 'Admin\Masters\ImportBrandsModelsController@import')->name('import-brands-models.import');

    // Country
    Route::resource('/master/countries', 'Admin\Masters\CountryController');
    Route::get('master/countries', 'Admin\Masters\CountryController@index')->name('countries.index');
    Route::get('master/countries-search', 'Admin\Masters\CountryController@search')->name('admin.countries_search');
    Route::get('master/delete-countries/{id}', 'Admin\Masters\CountryController@delete')->name('countries.delete');
    Route::get('master/countries/create', 'Admin\Masters\CountryController@create')->name('countries.create');

});

Route::get('static/content/{id}', 'MobileTermAndSeriveceUrl@termAndService');
Route::get('content/{id}', 'MobileTermAndSeriveceUrl@webtermAndService');
require_once('web_customer.php');

Route::get('/sk',function(){
    Artisan::call('cache:clear');
    Artisan::call('config:cache');
    Artisan::call('config:clear');

resources/views/admin/modules/cars/list.blade.php
@extends('admin.layouts.master')
@section('content')
<div class="page-title-box">
    <div class="row align-items-center">
        <div class="col-sm-6">
            <h4 class="page-title"> &nbsp</h4>
            <!-- <h4 class="page-title"> {{ __('l.members') }}</h4> -->
        </div>
        <div class="col-sm-6">
            <div class="float-right d-md-block">
                 
                <a href="{{ route('car.create')}}">
                    <button class="btn btn-primary arrow-none waves-effect waves-light" type="button">
                        <i class="fas fa-plus"></i> @lang('l.add') @lang('l.car')
                    </button>
                </a>
                 
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <h4 class="mt-0 header-title m-b-30">{{ __('l.car') }} {{ __('l.list') }}</h4>
                @include('admin.partials.messages')
                <div class="table-responsive table-full-width">
                    <div style="overflow: auto;">
                        <form action="{{ route('car.search')}}" method="GET">
                            <div class="row"> 
                                <div class="col-md-12">
                                    <div class="col-md-3" style="float:left;">
                                        <div class="form-group">
                                            <input type="text" name="owner_name" maxlength="250" class="form-control" placeholder="Owner First Name"
                                                @if(isset($name)) value="{{ $name }}" @endif autocomplete="off">
                                        </div>
                                    </div>
                                    <div class="col-md-3" style="float:left;">
                                        <div class="form-group">
                                            <input type="text" name="brand" maxlength="250" class="form-control" placeholder="Brand"
                                                @if(isset($brand)) value="{{ $brand }}" @endif autocomplete="off">
                                        </div>
                                    </div>
                                    <div class="col-md-3" style="float:left;">
                                        <div class="form-group">
                                            <input type="text" name="model" maxlength="250" class="form-control" placeholder="Model"
                                                @if(isset($model)) value="{{ $model }}" @endif autocomplete="off">
                                        </div>
                                    </div>
                                    <div class="col-md-3" style="float:left;">
                                        <div class="form-group">
                                            <input type="text" name="year" maxlength="250" class="form-control" placeholder="Model Year"
                                                @if(isset($year)) value="{{ $year }}" @endif autocomplete="off">
                                        </div>
                                    </div>
                                    <div class="col-md-3" style="float:left;">
                                        <div class="form-group"><br>
                                            <input type="text" name="color" maxlength="250" class="form-control" placeholder="Color"
                                                @if(isset($color)) value="{{ $color }}" @endif autocomplete="off">
                                        </div>
                                    </div>
                                    <div class="col-md-3" style="float:left;">
                                        <div class="form-group">
                                        <small class="form-text text-muted mt-0" style="color: #9ca8b3 !important;  font-size: 13px;">Available from :</small>
                                            <input type="date" name="available_from_date"  class="form-control" placeholder="Available From Date"
                                                @if(isset($available_from_date)) value="{{ $available_from_date }}" @endif autocomplete="off">
                                        </div>
                                    </div>
                                    <div class="col-md-3" style="float:left;">
                                        <div class="form-group">
                                        <small class="form-text text-muted mt-0" style="color: #9ca8b3 !important;  font-size: 13px;">Available to :</small>
                                            <input type="date" name="available_to_date" class="form-control" placeholder="Available To Date"
                                                @if(isset($available_to_date)) value="{{ $available_to_date }}" @endif autocomplete="off">
                                        </div>
                                    </div>
                                    <div class="col-md-3" style="float:left;">
                                        <div class="form-group"><br>
                                            <button class="btn btn-primary dropdown-toggle arrow-none waves-effect waves-light"
                                                type="submit"><i class="fa fa-search"></i> Search</button>
                                        </div>
                                    </div>
                                </div> 
                            </div>
                        </form>
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>@lang('l.#')</th>
                                    <th>Owner @lang('l.name')</th>
                                    <th>@lang('l.brand') @lang('l.name')</th>
                                    <th>@lang('l.model') @lang('l.name')</th>
                                    <th>@lang('l.color')</th>
                                    <th>@lang('l.model') Year</th>
                                    <th>Available From Date </th>
                                    <th>Available From Time </th>
                                    <th>Available To Date </th>
                                    <th>Available To Time </th>
                                    <th>Price/day</th>
                                   <!--  <th>Total Price</th> -->
                                    <th>Status</th>
                                    <th>Action</th>                                    
                                </tr>
                            </thead>
                            <tbody id="tbody">
                                @include('admin.modules.cars.tbody')
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="img-modal" tabindex="-1" role="dialog" aria-labelledby="edit-modal-label"
    aria-hidden="true">
    <div class="modal-dialog modal-md" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title mt-0">Change Car Status</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
            </div>
            <div class="modal-body" style="height: 100%;">
                <div class="alert" id="message" style="display: none"></div>
                <div class="alert ajaxmsg" style="display: none"></div>
                <form method="post" action="{{route('car.listingStatus')}}" enctype="multipart/form-data">
                    {{ csrf_field() }}
                    <div class="form-group">
                        <div class="row">
                            <div class="col-12 col-md-8 ">
                           
                                <input type="radio" name="listStatus" class="approve" value="approve"> Approve                             
                                <br><input type="radio" name="listStatus" class="reject" value="reject"> Reject                              
                                <input type="hidden" name="carid" id="car_id">  
                            </div>
                        </div><br>
                        <div class="row reason" id="" style="display:none;">
                            <div class="col-12 col-md-8 ">
                            <label for="reason">Please Enter Reason for Reject</label>
                            <textarea name="reason" cols="60" rows="7"></textarea>
                            </div>
                        </div>
                        <!-- <div class="text-center py-2 white">
                            <input  class="btn btn-primary waves-eff" value="Upload">
                        </div> -->

                    </div>
                </div>        
            <br/> 
            <div class="modal-footer"><button type="submit" name="upload" id="upload" class="btn btn-primary">Save</button> <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button></div>
        </form>               
        </div>
        
    </div>
    
</div>
@endsection

@section('script')
<script>
function change_status(id){       
    var inputF = document.getElementById("car_id");   
    inputF.setAttribute('value', id); 
    $('#img-modal').modal('show');
}
</script>
<script>
    $(function () {
        $(".reject").change(function () {             
            if ($(this.checked)) {
                $(".reason").show();
            } else {
                $(".reason").hide();
            }
        });

        $(".approve").change(function () {
           if ($(this.checked)) {
                $(".reason").hide();
            }  
        });
    });
    
</script>
@if(count($items) > 0)
    
    @include('lazyloading.loading')
    
@endif
@endsection

resources/views/admin/modules/cars/tbody.blade.php
@php 
use App\Models\Cars;
$jsoncurrency = currencyConverter();
@endphp
@if(!empty($items))

@forelse($items as $item)

    @php if($item->currency == 'USD'){
            $icon =  '$ ' ;
        }elseif($item->currency == 'EURO'){
            $icon = '&euro; '; 
        }else{
            $icon = $item->currency.' '; 
        } 
    @endphp  
<tr>
    <td>{{(($items->currentPage() * $items->perPage()) + $loop->iteration) - $items->perPage()}}</td>
    {{--<td ><a href="{{ route('car.show',  $item->id)}}" class="link" title="See Details">{{$item->full_name}}</a></td>--}}
    <td>{{isset($item->user->full_name ) ? $item->user->full_name : ''}} </td>
    <td>{{ isset($item->brand->name ) ? $item->brand->name :''}}</td>
    <td>{{isset($item->model->name) ? $item->model->name : ''}}</td>
    <td>{{isset($item->color->name) ? $item->color->name : ''}}</td>
    <td>{{isset($item->year) ? $item->year : ''}}</td>
    <!-- <td>{{isset($item->available_from_date) ? $item->available_from_date : ''}}</td> -->
    <td>{{isset($item->available_from_date) ? getCurrentTimezoneDate($item->available_from_date) : ''}}</td>
    <!-- <td>{{isset($item->available_from_date) ? date('d-M-Y ', strtotime($item->available_from_date)) : ''}}</td> -->
    <td>{{isset($item->available_from_time) ? getCurrentTimezoneTime($item->available_from_time) : ''}}</td>
    <!-- <td>{{isset($item->available_from_time) ? date('H:m:i', strtotime($item->available_from_time)) : ''}}</td> -->
    <td>{{isset($item->available_to_date) ? getCurrentTimezoneDate($item->available_to_date) : ''}}</td>
    <td>{{isset($item->available_to_time) ? getCurrentTimezoneTime($item->available_to_time) : ''}}</td>
    <td>{!! isset($item->price_per_day) ? '$'.getCurrencyFromUser('USD', 'USD', $item->currency, $item->price_per_day, $jsoncurrency) :"" !!}</td>
    <!-- <td>{!! isset($item->price_per_day) ? $icon.$item->price_per_day :"" !!}</td> -->
     {{-- <!-- <td>{!! isset($item->total_price) ? $icon.$item->total_price :"" !!}</td> -->--}}
      

    <td>
    <a href="javascript:void(0)" id= "{{$item->id}}" data-list-status = "{{$item->listing_status}}" @if($item->listing_status != '1') onclick="change_status(this.id)" @endif >
    <?php if($item->listing_status == 0) { echo '<span class="badge-warning badge mr-2">Pending</span>'; } else if($item->listing_status == 1) { echo '<span class="badge-success badge mr-2">Approved</span>'; }
     elseif($item->listing_status == 2){  echo '<span class="badge-danger badge mr-2">Rejected</span>'; } ?></a>
    
    </td>     
    <td>
        <div class="btn-group" role="group" aria-label="...">
            @if($item->listing_status != 1)
            <a href="{{ route('car.edit', $item->id)}}" class="btn btn-default" title="Edit"><i
                    class="far fa-edit"></i></a>
            @endif

            @if($item->status == 1)
            <a href="{{ route('car.status',[ 'id' => $item->id,'status' => $item->status])}}"
                class="btn btn-default" title="Active"><i class="fas fa-check text-success"></i></a>
            @else
            <a href="{{ route('car.status',[ 'id' => $item->id,'status' => $item->status])}}"
                class="btn btn-default" title="Inactive"><i class="fas fa-times text-danger"></i></a>
            @endif
            @if(!$item->is_rented)
            <a href="{{ route('car.delete',$item->id)}}" class="btn btn-default" title="Delete"><i
                    class="far fa-trash-alt"></i></a>
            @endif
            <a href="{{ route('car.show',$item->id)}}" class="btn btn-default link" title="See Details">
            <i class="fas fa-eye"></i></a>
        </div>
    </td>
    
</tr>
@empty
<tr>
    @if($items->currentPage() == $items->lastPage())
    <td colspan="14" align="center"> {{ __('l.car_not_found') }}</td>
    @else
        <td colspan="14" align="center"> {{ __('l.no_more_record') }}</td>
    @endif
</tr>
@endforelse
@else
<tr>
    <td colspan="14" align="center"> {{ __('l.car_not_found') }}</td>
</tr>
@endif