routes/front.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
 
// Route::get('/', function () {
//     return view('welcome');
// });

//Nurshing
Route::get('/', "Front\HomeController@getNursing")->name('main');
Route::get('nursing/', "Front\HomeController@searchNursing")->name('search.nursing');
Route::get('doctor', "Front\HomeController@searchDoctor")->name('search.doctor');
Route::get('doctor-availability', "Front\HomeController@searchDoctorAvailability")->name('doctor.availability');
// Route::get('doctor/search/data', 'Admin\DoctorController@search')->name('doctor.search');

Route::get('nursing-details/{id}', "Front\HomeController@nursingDetails")->name('nursing.list.details');
Route::get('create-appointment/', "Front\HomeController@createAppointment")->name('book.appointment');
//Book Appointment (Save)
Route::post('book-appointment/', "Clinics\PatientDashboardController@bookAppointment")->name('create.appointment');
Route::group(['middleware' =>'auth'], function(){
    Route::get('appointment-status/{id}/{status}', "Front\HomeController@bookingStatus")->name('booking.status');
});

Route::get('/plan-details/{planid}', "Front\HomeController@featuredPlan")->name('featured.plan');
Route::post('/hospital-registration', "Front\PaymentController@store")->name('payment.store');
Route::get('/payment-success/{nhid}', "Front\PaymentController@paymentSuccess")->name('payment.thankyou');
Route::post('/newsletter-save', "Front\NewsLetterController@store")->name('newsletter.store');

/*Doctor Dashboard*/
Route::group(['prefix' => 'clinic','middleware' =>'auth' ], function(){
    //DropZone
    Route::get('galleryimage/fetch/{nhid}', 'Admin\NursingHomeController@fetch')->name('gallery_dropzone.fetch');
    Route::get('galleryimage/delete', 'Admin\NursingHomeController@deleteImage')->name('gallery_dropzone.delete');

    //Change Profile For All Types user
    Route::post('/user-profile', "Clinics\DoctorDashboardController@action")->name('change_profile_pic');

    //use Middleware AdminControl
    Route::group(['prefix' => 'admin', 'middleware' =>'NursingHomeControl'], function(){
        Route::get('/dashboard', "Clinics\ClinicDashboardController@index")->name('nursing.dashboard');
        Route::get('/appointments', "Clinics\ClinicDashboardController@nursingAppointments")->name('nursing_all.appointments');
        Route::get('/patients', "Clinics\ClinicDashboardController@myPatients")->name('nursing.patients');
        Route::get('/patient-search', "Clinics\ClinicDashboardController@search")->name('nursing_patient.search');
        Route::get('/profile', "Clinics\ClinicDashboardController@profileView")->name('nursing.profile.view');
        Route::match(['GET', 'POST'],'/update-profile', "Clinics\ClinicDashboardController@profileUpdate")->name('nursing.profile.update');
        Route::resource('/nursing-doctor', "Clinics\NursingDoctorController");
        Route::get('nursing-doctor/{id}/{status}', 'Clinics\NursingDoctorController@status')->name('nursing-doctor.status');

    });
    //use Middleware Dr.Control
    Route::group(['prefix' => 'doctor', 'middleware' =>'DoctorControl'], function(){
        Route::get('/appointments', "Clinics\DoctorDashboardController@myAppointments")->name('doctors_all.appointments');
        Route::get('/appointment/details/{id}', "Clinics\DoctorDashboardController@appointmentDetails")->name('doctor.appointment.details');
        Route::get('/patients', "Clinics\DoctorDashboardController@myPatients")->name('doctor.patients');
        Route::get('/patient-search', "Clinics\DoctorDashboardController@search")->name('doctor_patient.search');
        Route::get('/dashboard', "Clinics\DoctorDashboardController@index")->name('doctor.dashboard');
        Route::get('/profile', "Clinics\DoctorDashboardController@profileView")->name('doctor.profile.view');
        Route::match(['GET', 'POST'],'/update-profile', "Clinics\DoctorDashboardController@profileUpdate")->name('doctor.profile.update');
    });    

});

Route::group(['prefix' => 'clinic','middleware' =>['auth', 'PatientControl']], function(){
    Route::get('/patient-appointments', "Clinics\PatientDashboardController@myAppointments")->name('patient.appointments');
    Route::get('/patient-dashboard', "Clinics\PatientDashboardController@index")->name('patient.dashboard');
    // Route::get('appointment-status/{id}/{status}', "Clinics\PatientDashboardController@bookingStatus")->name('booking.status');
    //Profile saection
    Route::get('/patient-profile', "Clinics\PatientDashboardController@profileView")->name('patient.profile.view');
    Route::match(['GET', 'POST'],'/update-patient-profile', "Clinics\PatientDashboardController@profileUpdate")->name('patient.profile.update');
});
// Route::get('/skpayment-success', "Front\PaymentController@paymentSuccess")->name('payment.thankyou1');

    // echo "sdfdsaf";

Route::get('/search', function () {
    return view('front.search');
})->name('search');


Route::get('/list-car',"Auth\LoginController@mysiteUser")->name('customer-login');
Route::get('/user-login',"Auth\LoginController@siteFrontUser")->name('front-customer-login');
Route::get('/user-signup',"Auth\LoginController@siteFrontUserSignup")->name('front-customer-signup');
Route::post('/email-otp',"Auth\RegisterController@userVerification")->name('user.verify');

Route::get('/myLocation',"Front\CarController@currentLocation")->name('myLocation');

Route::group(['middleware' => 'FrontControl'], function(){    
    Route::get('/available-car',"Front\CarController@searchCar")->name('find-car');
    Route::get('/available-car-map',"Front\CarController@carsOnMap")->name('map-car');
    Route::get('/car-details',"Front\CarController@carDetails")->name('car.details');
    Route::get('/add-tocart',"Front\OrderController@fillCart")->name('add.to.cart');
    Route::post('/order-now',"Front\OrderController@saveOrder")->name('order.now');

    //Route::get('stripe', 'Front\OrderController@PayNow')->name('pay.now');
    Route::get('stripe', 'Front\OrderController@stripePost')->name('stripe.post');
    
});
//paypal
Route::get('PayPal', 'Front\OrderController@paypalPost')->name('paypal-post');


Route::get('payment', 'Front\PayPalController@payment')->name('payment');
Route::get('cancel', 'Front\PayPalController@cancel')->name('payment.cancel');
Route::get('payment/success', 'Front\PayPalController@success')->name('payment.success');



Route::get('/pdfdownload/{url}',"Front\OrderController@pdfDownload");


Route::get('/how-it-works',function () {
    return view('front.sample-page');
})->name('how-it-works');


Route::get('/terms-of-service',function () {
    return view('front.term-of-service');
})->name('term.service');

Route::get('/privacy-policy',function () {
    return view('front.privacy-policy');
})->name('privacy.policy');

Route::get('/login/{social}','Auth\LoginController@socialLogin')->where('social','twitter|facebook|linkedin|google|github|bitbucket');
Route::get('/login/{social}/callback','Auth\LoginController@handleProviderCallback')->where('social','twitter|facebook|linkedin|google|github|bitbucket');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('locale/{locale}', function ($locale){
    Session::put('locale', $locale);
    return redirect()->back();
});

include('front.php');

Route::get('/admin', function () {
    return view('auth.login');
});
Auth::routes();
Auth::routes(['verify' => true]);

Route::get('/home', 'Controller@index')->name('home');
Route::get('admin/masters/model-by-brand', 'Admin\Masters\ModelController@modelByBrand')->name('get-model-by-brand-ajax');
//Route::get('dashboard', 'Admin\DashboardController@index')->name('dashboard');

//drozone auto upload
Route::post('nursinghome/gallery-image', 'Admin\NursingHomeController@createGalleryImage')->name('projects.storeMedia');
Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'AdminControl']], function () {
    Route::get('dashboard', 'Admin\DashboardController@index')->name('admin.panel');

    Route::resource('profile', 'Admin\ProfileController', ['names' => [
        'create' => 'adminprofile.create',
        'index' => 'adminprofile.index',
        'update' => 'adminprofile.update',
        'edit' => 'adminprofile.edit',
        'store' => 'adminprofile.store',
        'show' => 'adminprofile.show',
        'destroy' => 'adminprofile.destroy',
    ]]);
    // Route::post('profilepic', 'Admin\ProfileController@action')->name('change_profile_pic');
    
    //Speciality
    Route::resource('masters/speciality', 'Admin\Masters\SpecialityController');
    Route::get('masters/speciality/search/data', 'Admin\Masters\SpecialityController@search')->name('admin.speciality_search');
    Route::get('masters/delete-speciality/{id}', 'Admin\Masters\SpecialityController@delete')->name('speciality.delete');
    Route::get('masters/speciality/{id}/{status}', 'Admin\Masters\SpecialityController@status')->name('speciality.status');
   
    //Departments
    Route::resource('masters/departments', 'Admin\Masters\DepartmentController');
    Route::get('masters/departments/search/data', 'Admin\Masters\DepartmentController@search')->name('admin.departments_search');
    Route::get('masters/delete-departments/{id}', 'Admin\Masters\DepartmentController@delete')->name('departments.delete');
    Route::get('masters/departments/{id}/{status}', 'Admin\Masters\DepartmentController@status')->name('departments.status');
    
    //Equipments
    Route::resource('masters/equipments', 'Admin\Masters\EquipmentController');
    Route::get('masters/equipments/search/data', 'Admin\Masters\EquipmentController@search')->name('admin.equipments_search');
    Route::get('masters/delete-equipments/{id}', 'Admin\Masters\EquipmentController@delete')->name('equipments.delete');
    Route::get('masters/equipments/{id}/{status}', 'Admin\Masters\EquipmentController@status')->name('equipments.status');
    
    //subscription plans
    Route::resource('masters/plans', 'Admin\Masters\SubscriptionPlansController');
    Route::get('masters/plans/search/data', 'Admin\Masters\SubscriptionPlansController@search')->name('admin.plan_search');
    Route::get('masters/delete-plans/{id}', 'Admin\Masters\SubscriptionPlansController@delete')->name('plans.delete');
    //settings
    Route::resource('settings', 'Admin\SettingController');
    //Colors
    Route::resource('masters/colors', 'Admin\Masters\ColorsController');
    Route::get('masters/colors/search/data', 'Admin\Masters\ColorsController@search')->name('admin.colors_search');
    Route::get('masters/delete-colors/{id}', 'Admin\Masters\ColorsController@delete')->name('colors.delete');
    Route::get('masters/colors/{id}/{status}', 'Admin\Masters\ColorsController@status')->name('colors.status');

    //Engine Types
    Route::resource('masters/engine-types', 'Admin\Masters\EngineTypesController');
    Route::get('masters/engine-types/search/data', 'Admin\Masters\EngineTypesController@search')->name('admin.type_search');
    Route::get('masters/delete-engine-types/{id}', 'Admin\Masters\EngineTypesController@delete')->name('engine-types.delete');
    Route::get('masters/engine-types/{id}/{status}', 'Admin\Masters\EngineTypesController@status')->name('engine-types.status');

    //Vehicle Types
    Route::resource('masters/vehicle-types', 'Admin\Masters\VehicleTypesController');
    Route::get('masters/vehicle-types/search/data', 'Admin\Masters\VehicleTypesController@search')->name('admin.vehicle-type_search');
    Route::get('masters/delete-vehicle-types/{id}', 'Admin\Masters\VehicleTypesController@delete')->name('vehicle-types.delete');
    Route::get('masters/vehicle-types/{id}/{status}', 'Admin\Masters\VehicleTypesController@status')->name('vehicle-types.status');

    //Transmission
    Route::resource('masters/transmission', 'Admin\Masters\TransmissionController');
    Route::get('masters/transmission/search/data', 'Admin\Masters\TransmissionController@search')->name('admin.transmission_search');
    Route::get('masters/delete-transmission/{id}', 'Admin\Masters\TransmissionController@delete')->name('transmission.delete');
    Route::get('masters/transmission/{id}/{status}', 'Admin\Masters\TransmissionController@status')->name('transmission.status');
  
    //Model
    
    Route::resource('masters/model', 'Admin\Masters\ModelController');
    Route::get('masters/model/search/data', 'Admin\Masters\ModelController@search')->name('admin.model_search');
    Route::get('masters/delete-model/{id}', 'Admin\Masters\ModelController@delete')->name('model.delete');
    Route::get('masters/model/{id}/{status}', 'Admin\Masters\ModelController@status')->name('model.status');
    
   
    /* //Cars
    Route::resource('masters/car', 'Admin\Masters\CarController');
    Route::get('masters/car/search/data', 'Admin\Masters\CarController@search')->name('admin.car_search');
    Route::get('masters/delete-car/{id}', 'Admin\Masters\CarController@delete')->name('car.delete');
    Route::get('masters/car/{id}/{status}', 'Admin\Masters\CarController@status')->name('car.status'); */
    
    //Nursing Home
    Route::resource('nursinghome', 'Admin\NursingHomeController');
    Route::get('nursinghome/search/data', 'Admin\NursingHomeController@search')->name('nursinghome.search');
    Route::get('delete-nursinghome/{id}', 'Admin\NursingHomeController@delete')->name('nursinghome.delete');
    Route::get('nursinghome/{id}/{status}', 'Admin\NursingHomeController@status')->name('nursinghome.status');
    // Route::post('nursinghome/gallery-image', 'Admin\NursingHomeController@createGalleryImage')->name('projects.storeMedia');
    Route::get('gallery-image/fetch/{nhid}', 'Admin\NursingHomeController@fetch')->name('dropzone.fetch');
    Route::get('gallery-image/delete', 'Admin\NursingHomeController@deleteImage')->name('dropzone.delete');

    //Doctors
    Route::resource('doctor', 'Admin\DoctorController');
    Route::get('doctor/search/data', 'Admin\DoctorController@search')->name('doctor.search');
    Route::get('delete-doctor/{id}', 'Admin\DoctorController@delete')->name('doctor.delete');
    Route::get('doctor/{id}/{status}', 'Admin\DoctorController@status')->name('doctor.status');
    //Patient
    Route::resource('patient', 'Admin\PatientController');
    Route::get('patient/search/data', 'Admin\PatientController@search')->name('patient.search');
    Route::get('delete-patient/{id}', 'Admin\PatientController@delete')->name('patient.delete');
    Route::get('patient/{id}/{status}', 'Admin\PatientController@status')->name('patient.status');
    
    //Daynamic Contents translation manager
    Route::get('site-contents', 'Admin\LangContentsController@index')->name('contents.index');
    //Cars
    Route::resource('car', 'Admin\CarController');
    Route::get('car/search/data', 'Admin\CarController@search')->name('car.search');
    Route::get('delete-car/{id}', 'Admin\CarController@delete')->name('car.delete');
    Route::get('car/{id}/{status}', 'Admin\CarController@status')->name('car.status');
    Route::post('car/list-status/', 'Admin\CarController@listingStatus')->name('car.listingStatus');
    
    //Orders
    Route::resource('order', 'Admin\OrderController');
    Route::get('order/search/data', 'Admin\OrderController@search')->name('order.search');
    Route::get('order/{id}/{status}', 'Admin\OrderController@orderStatus')->name('order.status');

    //Account
    Route::resource('account', 'Admin\AccountController');
    Route::get('account/search/data', 'Admin\AccountController@search')->name('account.search');
    Route::get('account/owner-payment/{id}/{owner_payment}', 'Admin\AccountController@ownerPayment')->name('account.owner_payment_status');
    //Account
    Route::resource('settings', 'Admin\SettingController');

    //Import region
    Route::get('masters/import-brands-models', 'Admin\Masters\ImportBrandsModelsController@index')->name('import-brands-models.index');
    Route::post('masters/import-brands-models', 'Admin\Masters\ImportBrandsModelsController@import')->name('import-brands-models.import');

    // Country
    Route::resource('/master/countries', 'Admin\Masters\CountryController');
    Route::get('master/countries', 'Admin\Masters\CountryController@index')->name('countries.index');
    Route::get('master/countries-search', 'Admin\Masters\CountryController@search')->name('admin.countries_search');
    Route::get('master/delete-countries/{id}', 'Admin\Masters\CountryController@delete')->name('countries.delete');
    Route::get('master/countries/create', 'Admin\Masters\CountryController@create')->name('countries.create');

});

Route::get('static/content/{id}', 'MobileTermAndSeriveceUrl@termAndService');
Route::get('content/{id}', 'MobileTermAndSeriveceUrl@webtermAndService');

resources/views/admin/modules/nursinghomes/tbody.blade.php
@if(!empty($items))
@forelse($items as $item) 
<tr>
    <td>{{(($items->currentPage() * $items->perPage()) + $loop->iteration) - $items->perPage()}}</td>
    <td ><a href="{{ route('nursinghome.show',  $item->id)}}" class="link" title="See Details">{{$item->full_name}}</a></td>
    <td>{{ $item->email }}</td>
    <td>{{ isset($item->nursinghome->package) ? $item->nursinghome->package->name :''}}</td>
    <td> @php $order = isset($item->nursinghome->subscription_order) ? $item->nursinghome->subscription_order->where('order_status',1)->first() :'' @endphp
    {!! isset($order->plan_exp) && $order->plan_exp >= date('Y-m-d') ? date('M d, Y', strtotime($order->plan_exp)) : '<span class="badge-danger badge mr-2">Expired<span>' !!}
    </td>
    <!-- <td>@php 
           $month = date('Y-m-d', strtotime('+1 month')); @endphp {{$month}}</td> -->
    <!-- <td>{{ $item->country_code }} {{ $item->mobile }}</td>  -->
    <td><?php if($item->status == 1) { echo '<span class="badge-success badge mr-2">Active</span>'; } else{ echo '<span class="badge-danger badge mr-2">Inactive</span>'; } ?>
    </td> 
     
    <td>
        <div class="btn-group" role="group" aria-label="...">
            @if($item->id != Auth::user()->id)
             
            <a href="{{ route('nursinghome.edit',$item->id)}}" class="btn btn-default" title="Edit"><i
                    class="far fa-edit"></i></a>
             
            @if($item->status == 1)
            <a href="{{ route('nursinghome.status',[ 'id' => $item->id,'status' => $item->status])}}"
                class="btn btn-default" title="Active"><i class="fas fa-check text-success"></i></a>
            @else
            <a href="{{ route('nursinghome.status',[ 'id' => $item->id,'status' => $item->status])}}"
                class="btn btn-default" title="Inactive"><i class="fas fa-times text-danger"></i></a>
            @endif 
            <a href="{{ route('nursinghome.delete',$item->id)}}" class="btn btn-default" title="Delete"><i
                    class="far fa-trash-alt"></i></a>
           
            @endif
        </div>
    </td>
    
</tr>
@empty
<tr>
    @if($items->currentPage() == $items->lastPage())
    <td colspan="11" align="center">{{ __('l.nursing_home') }} {{ __('l.not_found') }}</td>
    @else
        <td colspan="10" align="center"> {{ __('l.no_more_record') }}</td>
    @endif
</tr>
@endforelse
@else
<tr>
    <td colspan="11" align="center">{{ __('l.nursing_home') }} {{ __('l.not_found') }}</td>
</tr>
@endif

resources/views/admin/modules/nursinghomes/view.blade.php
<?php use App\User; ?>
@extends('admin.layouts.master')
@section('content')
<div class="page-title-box">
    <div class="row align-items-center">
        <div class="col-sm-6">
            <h4 class="page-title">&nbsp</h4>
        </div>
        <div class="col-sm-6">
            <div class="float-right d-md-block">
               
                <a href="{{ route('nursinghome.edit', $item->id)}}">
                    <button class="btn btn-primary arrow-none waves-effect waves-light" type="button">
                        <i class="far fa-edit"></i> {{ __('l.edit') }}
                    </button>
                </a>
                
                <a href="{{ route('nursinghome.index')}}">
                    <button class="btn btn-primary arrow-none waves-effect waves-light" type="button">
                        <i class="fa fa-arrow-left"></i> @lang("l.back")
                    </button>
                </a>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <h4 class="mt-0 header-title">{{ __('l.nursing_home') }} Details</h4>
                <!-- <small class="form-text text-muted m-b-30" style="color: #9ca8b3 !important;  font-size: 15px;">(Your's user details)</small> -->
                @include('admin.partials.messages')
                <div class="row">
                    <div class="col-md-4">                        
                        <img alt="User Pic" src="{{ @fopen(\Url('storage/app/images/doctor/profile').'/'.$item->profile_pic, 'r') ? \Url('storage/app/images/doctor/profile/').'/'.$item->profile_pic : asset('public/nobody_user.jpg') }}"
                               id="profile_pic" class="" width="150" height="150">                         
                    
                    </div>
                    <div class="col-md-8">
                        <div class="table-responsive">
                            <table class="table mb-0">
                                <thead class="thead-light">
                                    <tr>
                                        <th colspan=2>User Details</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @if($item->first_name != '')
                                    <tr>
                                        <td><b>Name :</b></td>
                                        <td> {{ isset($item->first_name) ? $item->getFullNameAttribute() : '' }}</td>
                                    </tr>
                                    @endif
                                    <tr>
                                        <td><b>Contact No. :</b></td>
                                        <td>{{ isset($item->country_code) ? $item->country_code : '' }} {{ isset($item->mobile) ? $item->mobile : '' }}</td>
                                    </tr>
                                    
                                    <tr>
                                        <td><b>Email :</b></td>
                                        <td>{{ isset($item->email) ? $item->email : '' }}</td>
                                    </tr>

                                    <tr>
                                        <td><b>Designation :</b></td>
                                        <td>{{ isset($item->role->name) ? $item->role->name : '' }}</td>
                                    </tr>
                                    <tr>
                                        <td><b>Subscribed Plan :</b></td>
                                        <td>{!! isset($item->nursingHome) ? $item->nursingHome->package->name : '' !!}<br>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td><b>Plan Expiry date:</b></td>
                                        <td> @php $order = isset($item->nursinghome->subscription_order) ? $item->nursinghome->subscription_order->where('order_status',1)->first() :'' @endphp
                                        {!! isset($order->plan_exp) && $order->plan_exp >= date('Y-m-d') ? date('M d, Y', strtotime($order->plan_exp)) : '<span class="badge-danger badge mr-2">Expired<span>' !!}
                                        </td>
                                    </tr>
                                    <tr>
                                        <td><b>Address :</b></td>
                                        <td>{!! isset($item->address) ? $item->address : '' !!}<br>
                                        </td>
                                    </tr>

                                </tbody>
                            </table>
                        </div>
                    </div>
                    
                </div>
                <div class="row">
                    <div id="document-dropzone">
                    
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="table-responsive table-full-width">
                            <div style="overflow: auto;">
                                <table class="table table-striped">
                                    <thead>
                                        <tr>
                                            <th>@lang('l.#')</th>
                                            <th>@lang('l.name')</th>
                                            <th>@lang('l.email')</th>
                                            <th>@lang('l.mobile')</th>  
                                            <th>@lang('l.status')</th> 
                                            <th>Action</th>                                            
                                        </tr>
                                    </thead>
                                    <tbody id="tbody">
                                        @include('admin.modules.nursinghomes.view_tbody')
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@section('script')
<script>
        load_images();
        function load_images()
        {
            $.ajax({
            method :'Get'    ,
            url:"{{ route('dropzone.fetch', $item ? $item->nursing_home_id :'' ) }}",            
            success:function(data)
            {
                // $('#uploaded_image').html(data);
                if(data)
                $('#document-dropzone').append('<h3>Gallery Images</h3>');
                $('#document-dropzone').append(data);
                // $('#uploaded_image').append(data);
            }
            });
        }

        $(document).on('click', '.remove_image', function(){
            var name = $(this).attr('id');
            $.ajax({
            url:"{{ route('dropzone.delete') }}",
            data:{name : name},
            success:function(data){
                var row = $('#document-dropzone').find('.row');
                $('#document-dropzone').find('h3').remove();
                row.empty();
                load_images();
            }
            })
        });
    </script>
@endsection
@if(count($items) > 0)
    @section('script')
    @include('lazyloading.loading')
    @endsection
@endif

resources/views/admin/modules/nursinghomes/view_tbody.blade.php
@if(!empty($items))
@forelse($items as $item) 
<tr>
    <td>{{(($items->currentPage() * $items->perPage()) + $loop->iteration) - $items->perPage()}}</td>
    <td ><a href="{{ route('doctor.show',  $item->id)}}" class="link" title="See Details">{{$item->full_name}}</a></td>
    <td>{{$item->email}}</td>
    <td>{{$item->country_code}} {{$item->mobile}}</td> 
    <td><?php if($item->status == 1) { echo '<span class="badge-success badge mr-2">Active</span>'; } else{ echo '<span class="badge-danger badge mr-2">Inactive</span>'; } ?>
    </td> 
     
    <td>
        <div class="btn-group" role="group" aria-label="...">
            @if($item->id != Auth::user()->id)
             
            <a href="{{ route('doctor.edit',$item->id)}}" class="btn btn-default" title="Edit"><i
                    class="far fa-edit"></i></a>
             
            @if($item->status == 1)
            <a href="{{ route('doctor.status',[ 'id' => $item->id,'status' => $item->status])}}"
                class="btn btn-default" title="Active"><i class="fas fa-check text-success"></i></a>
            @else
            <a href="{{ route('doctor.status',[ 'id' => $item->id,'status' => $item->status])}}"
                class="btn btn-default" title="Inactive"><i class="fas fa-times text-danger"></i></a>
            @endif 
            <a href="{{ route('doctor.delete',$item->id)}}" class="btn btn-default" title="Delete"><i
                    class="far fa-trash-alt"></i></a>
           
            @endif
        </div>
    </td>
    
</tr>
@empty
<tr>
    @if($items->currentPage() == $items->lastPage())
    <td colspan="11" align="center"> {{ __('l.doctor') }} {{ __('l.not_found') }}</td>
    @else
        <td colspan="10" align="center"> {{ __('l.no_more_record') }}</td>
    @endif
</tr>
@endforelse
@else
<tr>
    <td colspan="11" align="center">{{ __('l.doctor') }} {{ __('l.not_found') }}</td>
</tr>
@endif